library(lubridate)
wd<-getwd()
temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp,method="curl")
data <- read.table(unz(temp, "household_power_consumption.txt"),na.strings="?", sep=";",)
unlink(temp)
## for local testing ## data<-read.csv("/Users/connorburleigh/Coursera/household_power_consumption.txt", sep=";",na.strings="?",stringsAsFactors=FALSE)
Date_and_Time<-paste(data$Date,data$Time)
Date_and_Time<-dmy_hms(Date_and_Time)
clean_data<-cbind(Date_and_Time, data)
relevant_data<-clean_data[clean_data$Date_and_Time >= ymd_hms("2007-2-1 00:00:00")& clean_data$Date_and_Time < ymd_hms("2007-2-3 00:00:00"),]
png("plot4.png", height=480, width = 480)
par(mfrow=c(2,2))
plot(relevant_data$Date_and_Time,relevant_data$Global_active_power,type="l",ylab="Global Active Power",xlab="")
plot(relevant_data$Date_and_Time,relevant_data$Voltage,type="l",ylab="Voltage",xlab="datetime")
plot(relevant_data$Date_and_Time,relevant_data$Sub_metering_1, type="l",ylab="", xlab="")

lines(relevant_data$Date_and_Time,relevant_data$Sub_metering_2,col="red")
lines(relevant_data$Date_and_Time,relevant_data$Sub_metering_3,col="blue")
title(ylab= "Energy sub metering")
legend('topright',legend=legend_headings, lwd = 1, col=c("black","red","blue"),bty="n")
plot(relevant_data$Date_and_Time,relevant_data$Global_reactive_power,type="l",ylab="Global_reactive_power", xlab="datetime")
dev.off()